abbr g 'git'
abbr ga 'git add'
abbr gb 'git branch -a'
abbr gbl 'git blame'
abbr gc 'git checkout'
abbr gcm 'git commit -m'
abbr gca 'git commit --amend'
abbr gco 'git checkout'
abbr gcp 'git cherry-pick'
abbr gd 'git diff'
abbr gf 'git fetch'
abbr gl 'git llog'
abbr gm 'git merge'
abbr gp 'git push'
abbr gpl 'git pull'
abbr gr 'git remote'
abbr gs 'git status'
abbr gst 'git stash'
abbr gbi 'git rebase --interactive'
abbr gro 'git reset --hard origin/master'
abbr grh 'git reset --hard HEAD'

abbr cls 'clear'
abbr cx 'chmod +x'

abbr psg 'ps aux | grep'

abbr pserv 'python3 -m http.server 8080'

abbr kc 'kubectl'
abbr kca 'kubectl apply -f'
abbr pkca 'pbpaste | kubectl apply -f -'
abbr ks 'kubens'
abbr kcp 'kubectl get pods -A'
abbr kcs 'kubectl get svc -A'

abbr dps 'docker ps'
